
services:
  liebkreis_db:
    image: postgres:15
    container_name: liebkreis_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  pya_backend:
    build: ./backend
    container_name: pya_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - liebkreis_db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: pya_frontend
    restart: always
    depends_on:
      - pya_backend
    ports:
      - "4200:4200"

volumes:
  postgres_data:  {}  